Remove python validation reusable workflow and replace with individual steps

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -29,9 +29,41 @@ jobs:
     needs:
       - check-auto-tagging-will-work
     permissions: write-all
-    uses: climatepolicyradar/reusable-workflows/.github/workflows/python-precommit-validator.yml@v13
-    with:
-      python-version: "3.10"
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.10"
+
+      - name: Install dependencies
+        run: |
+          pip install uv --no-cache-dir uv==0.6.16
+          uv sync --all-groups
+
+      - name: Export PYTHONPATH
+        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
+
+      - name: Check pyproject.toml package version matches
+        uses: climatepolicyradar/check-pyproject-package-version@v4
+
+      - name: Check code contains no FIXME's
+        run: |
+          git grep -r --no-color --line-number -e "FIXME" :^.github
+          if [[ $? -eq 0 ]]; then
+            # if we found any FIXME entries in checked in files, fail on main
+            exit 1
+          else
+            exit 0
+          fi
+        shell: bash {0}
+
+      - name: Trunk Check
+        uses: trunk-io/trunk-action@v1
+        with:
+          arguments: --ci
 
   test:
     if: |
